### ISSUE TITLE
导出抽卡记录错误

### ISSUE THREAD

**Issue by MoonShadow1976** [JamXi233/WaveTools#33]
2024/7/18 12:32:32 [1] 源:System.Private.CoreLib
错误标题:
堆栈跟踪:
   at WaveTools.Views.ToolViews.GachaView.ExportWWGF_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at WaveTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
内部异常:

结束代码:-2147467259
完整错误:
System.Runtime.InteropServices.COMException (0x80004005)
   at WaveTools.Views.ToolViews.GachaView.ExportWWGF_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at WaveTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)

**Comment by JamXi233** [comment]
使用管理员启动时[选择文件/保存文件]窗口无法打开，下一版本会修复。
