### ISSUE TITLE
更新依赖环境出错

### ISSUE THREAD

**Issue by wangyujie1025** [JamXi233/WaveTools#50]
![image](https://github.com/user-attachments/assets/5dd2c827-9d62-453f-bbd1-c4af8e19612e)
![image](https://github.com/user-attachments/assets/bab9fa94-008b-4d8f-89c2-a2f0454e6adf)

**Comment by SlipperSoar** [comment]
![image](https://github.com/user-attachments/assets/ebf9666b-5b7c-4733-8277-e5276e6235b4)

同样无法更新。系统为Win11

**Comment by Alexiszj** [comment]
2024/8/17 15:42:58 [1] 源:System.IO.Compression
错误标题:End of Central Directory record could not be found.
堆栈跟踪:
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at WaveTools.Views.FirstRunViews.FirstRunGetDepend.DependDownload_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at WaveTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
内部异常:

结束代码:-2146233087
完整错误:
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at WaveTools.Views.FirstRunViews.FirstRunGetDepend.DependDownload_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at WaveTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)

  初次打开安装依赖出现错误

**Comment by NooAcc** [comment]
可以试试手动更新：
1、下载[WaveToolsHelper_1.2.4.0](https://github.com/JamXi233/Releases/releases/download/WaveToolsHelper_1.2.4.0/WaveToolsHelper_1.2.4.0.zip)
2、解压覆盖到 `C:\Users\用户名\Documents\JSG-LLC\WaveTools\Depends\WaveToolsHelper` 文件夹

**Comment by Alexiszj** [comment]
> 可以试试手动更新： 1、下载[WaveToolsHelper_1.2.4.0](https://github.com/JamXi233/Releases/releases/download/WaveToolsHelper_1.2.4.0/WaveToolsHelper_1.2.4.0.zip) 2、解压覆盖到 文件夹`C:\Users\用户名\Documents\JSG-LLC\WaveTools\Depends\WaveToolsHelper`

已解决，谢谢作者，貌似问题是下载后无法解压，需要手动解压一下

**Comment by wangyujie1025** [comment]
> > 可以试试手动更新： 1、下载[WaveToolsHelper_1.2.4.0](https://github.com/JamXi233/Releases/releases/download/WaveToolsHelper_1.2.4.0/WaveToolsHelper_1.2.4.0.zip) 2、解压覆盖到 文件夹`C:\Users\用户名\Documents\JSG-LLC\WaveTools\Depends\WaveToolsHelper`
> 
> 已解决，谢谢作者，貌似问题是下载后无法解压，需要手动解压一下

是的，已解决，感谢
